# Dockerfile.edge
# Extend the base Dockerfile
FROM tracr_base_image

# Copy the requirements file
COPY requirements.edge.txt .

# Install edge-specific Python dependencies
RUN pip install -r requirements.edge.txt
