# config/fasterrcnnsplit.yaml

# ================================================================
# DEFAULT CONFIGURATIONS
# ================================================================
default:
  device: cuda
  font_path: config/fonts/DejaVuSans-Bold.ttf
  save_layer_images: false
  collect_metrics: false

# ================================================================
# LOGGING CONFIGURATIONS
# ================================================================
logging:
  log_level: INFO
  log_file: logs/app.log

# ================================================================
# MODEL CONFIGURATIONS
# ================================================================
model:
  model_name: fasterrcnn_resnet50_fpn
  version: v1
  pretrained: true
  weight_path: null
  input_size: [3, 800, 800]
  split_layer: -1
  save_layers: [0, 5, 10, 15]
  num_classes: 2
  mode: eval
  depth: 3
  flush_buffer_size: 50
  warmup_iterations: 5
  log_file: logs/fasterrcnn_model.log

# ================================================================
# DATASET CONFIGURATIONS
# ================================================================
dataset:
  name: "coco"
  root: "data/coco"
  class_names: "data/coco/coco_classes.txt"
  img_directory: "data/coco/images"
  transform: null
  max_samples: -1

# ================================================================
# DATALOADER CONFIGURATIONS
# ================================================================
dataloader:
  batch_size: 1
  shuffle: false
  num_workers: 4
  collate_fn: rcnn_collate

# ================================================================
# COMPRESSION CONFIGURATIONS
# ================================================================
compression:
  clevel: 5
  filter: SHUFFLE
  codec: ZSTD
